# Generated by Django 3.0.8 on 2020-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='unlogged')),
                ('jsondata', models.TextField()),
            ],
        ),
    ]
