# Generated by Django 3.0.8 on 2020-07-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tableuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableuser',
            old_name='jsondata',
            new_name='json_data',
        ),
    ]
